### ISSUE TITLE
Question about card game functionality

### ISSUE THREAD

**Issue by ejkkan** [hewad-mubariz/reactnative-50-days#2]
Hey! 
Love this repo and the work you're doing.

I have a question about the card game project.
If you were to make move a specific card to a specific location. For example; card at position 2 will be laid on top of the card with position 5.
Thanks

**Comment by hewad-mubariz** [comment]
Hey,

Thanks for your interest and kind words about the project!

To achieve the card movement you're asking about, gesture handling and animation modifications would be needed.

You'd use a library like ```react-native-gesture-handler``` for handling drag-and-drop gestures. Each card would need to be wrapped in a ```PanGestureHandler``` with the ```onGestureEvent``` prop to manage gestures.

To smoothly animate the movement, you'd interpolate the card's position from its original position to the new one using an animated value.

Moreover, using snap points with the  ```react-native-reanimated``` library would be a great idea to make the cards' movement feel more natural and intuitive. When the card is released after dragging, it would "snap" into its intended position.

Managing the zIndex of the card during the move would ensure it appears above the other cards.

I hope this helps, and I encourage you to explore the react-native-gesture-handler and react-native-reanimated libraries for more details!

Thanks
